name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  build-status: 
    description: 'status of test or build'
    required: true
    default: '1'
runs:
  using: 'docker'
  image: 'dockerfile'
  args: 
    - ${{ inputs.build-status}}